name: Build docker image
on: 
  push: 
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: set up golang
        uses: actions/setup-go@v2-beta
        with:
            go-version: 1.13.10
      - name: check out code
        uses: actions/checkout@v2
      - name: build docker image
        run: docker build -t dictybase/auto-deploy:$(git rev-parse --short HEAD) -f build/package/Dockerfile .
      - name: login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: push to docker hub
        run: docker push dictybase/auto-deploy:$(git rev-parse --short HEAD)
