name: Docker image build and push
on: 
  push:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: image build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD  }}
          repository: dictybase/auto-deploy
          add_git_labels: true
          tag_with_sha: true
          dockerfile: build/package/Dockerfile
