name: Deploy to kubernetes
on:
  deployment:
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: setup google cloud sdk
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SA_KEY }}
          export_default_credentials: true
      - name: get credentials
        run: gcloud container clusters get-credentials siddkube --zone us-central1-a
      - name: set up helm 
        uses: azure/setup-helm@v1
        with:
          version: 'v2.16.1'
      - name: check helm connectivity
        run: helm version
